# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MrAgentAi < Formula
  desc "Multi-Agent AI Skill Installer — installs agent skills into any project."
  homepage "https://github.com/SaidHernandez/mr-agent-ai"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SaidHernandez/mr-agent-ai/releases/download/v1.6.0/mr-agent-ai_1.6.0_darwin_amd64.tar.gz"
      sha256 "ac2fb02f530e9778c36ff74e55da2f9019175164416c7ab59110925d99b578d0"

      define_method(:install) do
        bin.install "mr-agent-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SaidHernandez/mr-agent-ai/releases/download/v1.6.0/mr-agent-ai_1.6.0_darwin_arm64.tar.gz"
      sha256 "1dfbb7a617961b9532ef528bb8d4f846b4fff1dc897ed21041ab329e845cd0a2"

      define_method(:install) do
        bin.install "mr-agent-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SaidHernandez/mr-agent-ai/releases/download/v1.6.0/mr-agent-ai_1.6.0_linux_amd64.tar.gz"
      sha256 "5edde09eae46e69d7b693e80776f2d0c844c6421ad9dec40b68a4dabf27e1013"
      define_method(:install) do
        bin.install "mr-agent-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SaidHernandez/mr-agent-ai/releases/download/v1.6.0/mr-agent-ai_1.6.0_linux_arm64.tar.gz"
      sha256 "87a00dd5d6e51ea8416b796b410fbaf3ad1a781e5afff5fd06b7167f1720ed86"
      define_method(:install) do
        bin.install "mr-agent-ai"
      end
    end
  end

  test do
    system "#{bin}/mr-agent-ai", "--help"
  end
end
