# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MrAgentAi < Formula
  desc "Multi-Agent AI Skill Installer — installs agent skills into any project."
  homepage "https://github.com/SaidHernandez/mr-agent-ai"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SaidHernandez/mr-agent-ai/releases/download/v1.0.0/mr-agent-ai_1.0.0_darwin_amd64.tar.gz"
      sha256 "54bbee5ec75d53fa7174983c9d8b917598285a61df98e64b65cc05e9ad5b28f2"

      define_method(:install) do
        bin.install "mr-agent-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SaidHernandez/mr-agent-ai/releases/download/v1.0.0/mr-agent-ai_1.0.0_darwin_arm64.tar.gz"
      sha256 "7587f21222cd0363dabb9e8a267cf4f2baa40c3fa1d9bcb8c95514c9849cb7da"

      define_method(:install) do
        bin.install "mr-agent-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SaidHernandez/mr-agent-ai/releases/download/v1.0.0/mr-agent-ai_1.0.0_linux_amd64.tar.gz"
      sha256 "bdc508955edcd6a285e4b426b21409363c5f035e29c93f0acaad3da223f256e4"
      define_method(:install) do
        bin.install "mr-agent-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SaidHernandez/mr-agent-ai/releases/download/v1.0.0/mr-agent-ai_1.0.0_linux_arm64.tar.gz"
      sha256 "81837fe3c8dd33e8393e3664e4cc52ccb5ad1efa1c79eeaff2edfdfbeb5d8955"
      define_method(:install) do
        bin.install "mr-agent-ai"
      end
    end
  end

  test do
    system "#{bin}/mr-agent-ai", "--help"
  end
end
