name: SAST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  bandit:
    name: bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run bandit
        run: |
          pip install bandit
          bandit -r . -x ./tests,./venv,./.venv -ll
